/**
 * Entity-side QR mutual authentication utilities.
 *
 * Phase 1 — session creation:
 *   generateEntityQRSession() creates an ephemeral ECDSA key pair, signs
 *   "sessionId:challenge:sessionTimestamp" and returns everything needed to:
 *     a. PUT the registration to the relay  (registerEntitySession)
 *     b. Embed in the QR code so the wallet can self-verify WITHOUT trusting relay alone
 *
 * Phase 4 — verifying the wallet response:
 *   verifyWalletResponse() checks:
 *     - signedData format: "challenge:sessionId:entitySig:ethAddress:did:...:walletTimestamp"
 *     - challenge matches what was generated
 *     - sessionId matches
 *     - entitySig matches (wallet saw the real QR)
 *     - walletTimestamp is fresh (5 min window)
 *     - DID is RESOLVED from the authoritative wallet backend (resolve-did.php)
 *       → the POST body's `pk` field is NEVER trusted for key material
 *       → attacker cannot supply their own key and forge identity
 *     - ECDSA signature valid against the RESOLVED public key
 *   Returns the verified { did, ethAddress } on success, throws on failure.
 */

// ─── helpers ────────────────────────────────────────────────────────────────

function ab2b64(buffer: ArrayBuffer): string {
  const bytes = new Uint8Array(buffer);
  let s = '';
  for (let i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i]);
  return btoa(s);
}

async function signECDSA(privateKey: CryptoKey, data: string): Promise<string> {
  const sig = await crypto.subtle.sign(
    { name: 'ECDSA', hash: 'SHA-256' },
    privateKey,
    new TextEncoder().encode(data)
  );
  return ab2b64(sig);
}

// ─── Phase 1: entity generates authenticated QR session ─────────────────────

export interface EntityQRSession {
  /** Embed all of these in the QR code value. */
  qrPayload: {
    type: 'did-request';
    sessionId: string;
    challenge: string;
    entityPublicKey: JsonWebKey;
    entitySignature: string;
    sessionTimestamp: number;
  };
  /** PUT this to the relay so the wallet can cross-validate. */
  relayRegistration: {
    sessionId: string;
    entityPublicKey: JsonWebKey;
    entitySignature: string;
    sessionTimestamp: number;
  };
}

export async function generateEntityQRSession(): Promise<EntityQRSession> {
  // Generate ephemeral ECDSA P-256 key pair for this session only
  const keyPair = await crypto.subtle.generateKey(
    { name: 'ECDSA', namedCurve: 'P-256' },
    true,
    ['sign', 'verify']
  );

  const entityPublicKey = await crypto.subtle.exportKey('jwk', keyPair.publicKey) as JsonWebKey;
  // Remove private key material from exported JWK just in case
  delete (entityPublicKey as any).d;

  // Random session ID
  const sessionId = `session-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

  // Random 32-byte challenge (hex)
  const challengeBytes = new Uint8Array(32);
  crypto.getRandomValues(challengeBytes);
  const challenge = Array.from(challengeBytes).map(b => b.toString(16).padStart(2, '0')).join('');

  const sessionTimestamp = Date.now();

  // Entity signs own session data — wallet will verify this
  const entitySignature = await signECDSA(
    keyPair.privateKey,
    `${sessionId}:${challenge}:${sessionTimestamp}`
  );

  const qrPayload = {
    type: 'did-request' as const,
    sessionId,
    challenge,
    entityPublicKey,
    entitySignature,
    sessionTimestamp,
  };

  return {
    qrPayload,
    relayRegistration: {
      sessionId,
      entityPublicKey,
      entitySignature,
      sessionTimestamp,
    },
  };
}

/** Register the entity session on the relay via PUT. */
export async function registerEntitySession(
  reg: EntityQRSession['relayRegistration']
): Promise<void> {
  const res = await fetch('http://localhost:8000/qr-relay.php', {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(reg),
  });
  if (!res.ok) {
    throw new Error('Failed to register session on relay server');
  }
}

// ─── Phase 4: entity verifies wallet response ────────────────────────────────

/**
 * Verifies wallet's signed response.
 *
 * @param result        The raw relay response object (POST body mirror).
 * @param sessionId     The session ID generated by this entity.
 * @param challenge     The challenge generated by this entity.
 * @param entitySignature The entity's own ephemeral signature from the QR session.
 * @param didResolverUrl  Base URL of the wallet backend (default: http://localhost:8000).
 *
 * Returns `{ did, ethAddress }` on success, throws on failure.
 *
 * SECURITY: the `pk` field in `result` is NEVER used to verify the signature.
 * The public key is always fetched from the authoritative DID resolver, so an
 * attacker who supplies their own key in the POST body will fail verification.
 */
export async function verifyWalletResponse(
  result: any,
  sessionId: string,
  challenge: string,
  entitySignature: string,
  didResolverUrl = 'http://localhost:8000'
): Promise<{ did: string; ethAddress: string }> {
  const { signature, signedData } = result;

  if (!signature || !signedData) {
    throw new Error('Wallet response is missing required authentication fields.');
  }

  // ── Parse signedData ───────────────────────────────────────────────────────
  // Format: "challenge:sessionId:entitySig:ethAddress:did:...:walletTimestamp"
  //   index 0       = challenge
  //   index 1       = sessionId
  //   index 2       = entitySig
  //   index 3       = ethAddress  (Ethereum addresses never contain colons)
  //   index 4..n-1  = did         (may contain colons, e.g. did:zeroid:uuid)
  //   last          = walletTimestamp
  const parts         = (signedData as string).split(':');
  const sigChallenge  = parts[0];
  const sigSession    = parts[1];
  const sigEntitySig  = parts[2];
  const sigEthAddress = parts[3];
  const sigTimestamp  = parts[parts.length - 1];
  const sigDid        = parts.slice(4, parts.length - 1).join(':');

  if (sigChallenge  !== challenge)       throw new Error('Challenge mismatch');
  if (sigSession    !== sessionId)       throw new Error('Session mismatch');
  if (sigEntitySig  !== entitySignature) throw new Error('Entity signature mismatch — possible relay substitution attack');
  if (!sigEthAddress || !sigEthAddress.startsWith('0x'))
    throw new Error('Ethereum address missing or malformed in signed data');
  if (!sigDid.startsWith('did:'))        throw new Error('DID missing or malformed in signed data');
  if (Math.abs(Date.now() - Number(sigTimestamp)) > 5 * 60 * 1000)
    throw new Error('Wallet response timestamp expired');

  // ── Resolve DID from authoritative source ──────────────────────────────────
  // NEVER trust the pk field from the POST body — an attacker can replace it.
  // Always fetch the public key from the wallet backend database.
  let resolvedPk: JsonWebKey;
  let resolvedEthAddress: string;
  try {
    const res = await fetch(
      `${didResolverUrl}/resolve-did.php?did=${encodeURIComponent(sigDid)}`
    );
    const json = await res.json();
    if (!json.success || !json.publicKeyJwk) {
      throw new Error(json.message ?? 'DID not found');
    }
    resolvedPk         = json.publicKeyJwk as JsonWebKey;
    resolvedEthAddress = (json.ethAddress as string ?? '').toLowerCase();
  } catch (err: any) {
    throw new Error(`DID resolution failed for ${sigDid}: ${err.message}`);
  }

  // ── Verify ethAddress matches DB registration ─────────────────────────────────
  // Prevents a legitimate user from redirecting the NFT to an unregistered
  // address by signing their own signedData with their own key.
  if (sigEthAddress.toLowerCase() !== resolvedEthAddress) {
    throw new Error(
      'Ethereum address in signed payload does not match the registered address for this DID. ' +
      'Asset redirect attempt blocked.'
    );
  }

  // ── Defense-in-depth: cross-check removed intentionally ──────────────────
  // The POST body's `pk` field is attacker-controlled and omittable, so any
  // check against it is bypassable. Security comes entirely from the DID
  // resolution above. A `pk` field in the POST is simply ignored.

  // ── Verify ECDSA signature using the RESOLVED key ──────────────────────────
  const publicKey = await crypto.subtle.importKey(
    'jwk', resolvedPk,
    { name: 'ECDSA', namedCurve: 'P-256' }, false, ['verify']
  );
  const sigBytes = Uint8Array.from(atob(signature as string), c => c.charCodeAt(0));
  const valid = await crypto.subtle.verify(
    { name: 'ECDSA', hash: 'SHA-256' },
    publicKey, sigBytes,
    new TextEncoder().encode(signedData as string)
  );
  if (!valid) throw new Error('Invalid wallet ECDSA signature');

  return { did: sigDid, ethAddress: sigEthAddress };
}
