/**
 * Entity-side QR authentication utilities — symmetric secret approach.
 *
 * Because the QR code is generated and displayed locally, the entity can embed
 * a symmetric AES-GCM secret directly inside it.  The wallet (which scanned
 * the QR locally) encrypts its identity data with that secret and posts only
 * the ciphertext to the relay.  Only this entity, which holds the secret, can
 * decrypt it.
 *
 * Phase 1 — QR generation (generateEntityQRSession):
 *   Generates a fresh AES-GCM 256-bit key, a sessionId, a 32-byte challenge,
 *   and a sessionTimestamp.  The raw key bytes are base64-encoded into `secret`
 *   and embedded in the QR payload.  Only the sessionId is registered with the
 *   relay — no secret or key material ever leaves the local device via the relay.
 *
 * Phase 2 — wallet encrypts (wallet side):
 *   The wallet imports `secret` as an AES-GCM key and encrypts the JSON payload
 *   { did, ethAddress, challenge, sessionId, walletTimestamp }.
 *   It posts { sessionId, encrypted: { iv, ciphertext } } to the relay.
 *
 * Phase 3 — entity decrypts and verifies (verifyWalletResponse):
 *   Decrypts the AES-GCM blob with the in-memory secretKey.
 *   Validates challenge, sessionId, and walletTimestamp freshness (5-min window).
 *   Resolves the DID from the authoritative backend and verifies ethAddress.
 *   Returns { did, ethAddress } on success, throws on failure.
 */

// ─── helpers ────────────────────────────────────────────────────────────────

function ab2b64(buffer: ArrayBuffer): string {
  const bytes = new Uint8Array(buffer);
  let s = '';
  for (let i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i]);
  return btoa(s);
}
async function verifyECDSA(publicKeyJwk: JsonWebKey, data: string, b64Sig: string): Promise<boolean> {
  const key = await crypto.subtle.importKey(
    'jwk', publicKeyJwk, { name: 'ECDSA', namedCurve: 'P-256' }, false, ['verify']
  );
  const sigBytes = Uint8Array.from(atob(b64Sig), c => c.charCodeAt(0));
  return crypto.subtle.verify(
    { name: 'ECDSA', hash: 'SHA-256' },
    key, sigBytes, new TextEncoder().encode(data)
  );
}
// ─── Types ──────────────────────────────────────────────────────────────────

/** AES-GCM encrypted payload produced by the wallet and posted to the relay. */
export interface EncryptedPayload {
  /** AES-GCM IV (base64). */
  iv: string;
  /** AES-GCM ciphertext (base64) of the JSON identity payload. */
  ciphertext: string;
}

// ─── Phase 1: entity generates QR session ───────────────────────────────────

export interface EntityQRSession {
  /** Embed all of these in the QR code value. */
  qrPayload: {
    type: 'did-request';
    sessionId: string;
    challenge: string;
    sessionTimestamp: number;
    /**
     * Base64-encoded raw AES-GCM 256-bit key.
     * Wallet uses this to encrypt its identity data locally.
     */
    secret: string;
  };
  /** PUT this to the relay so the entity can poll for the wallet response. */
  relayRegistration: {
    sessionId: string;
    sessionTimestamp: number;
  };
  /**
   * The AES-GCM key kept in memory only — never sent to the relay.
   * Used in Phase 3 to decrypt the wallet's encrypted payload.
   */
  secretKey: CryptoKey;
}

export async function generateEntityQRSession(): Promise<EntityQRSession> {
  // Generate a fresh AES-GCM 256-bit symmetric key
  const secretKey = await crypto.subtle.generateKey(
    { name: 'AES-GCM', length: 256 },
    true,
    ['encrypt', 'decrypt']
  );

  // Export raw bytes → base64 for the QR payload
  const rawKey = await crypto.subtle.exportKey('raw', secretKey);
  const secret = ab2b64(rawKey);

  const sessionId = `session-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

  const challengeBytes = new Uint8Array(32);
  crypto.getRandomValues(challengeBytes);
  const challenge = Array.from(challengeBytes).map(b => b.toString(16).padStart(2, '0')).join('');

  const sessionTimestamp = Date.now();

  return {
    qrPayload: {
      type: 'did-request',
      sessionId,
      challenge,
      sessionTimestamp,
      secret,
    },
    relayRegistration: {
      sessionId,
      sessionTimestamp,
    },
    secretKey,
  };
}

/** Register the entity session on the relay via PUT. */
export async function registerEntitySession(
  reg: EntityQRSession['relayRegistration']
): Promise<void> {
  const res = await fetch('http://localhost:8000/qr-relay.php', {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(reg),
  });
  if (!res.ok) {
    throw new Error('Failed to register session on relay server');
  }
}

// ─── Phase 3: entity decrypts and verifies wallet response ──────────────────

/**
 * Decrypts and validates the wallet's relay response.
 *
 * @param result         Raw relay response object — must contain `encrypted: { iv, ciphertext }`.
 * @param sessionId      The session ID generated by this entity.
 * @param challenge      The challenge generated by this entity.
 * @param secretKey      The AES-GCM key generated alongside the QR (never leaves memory).
 * @param didResolverUrl Base URL of the wallet backend (default: http://localhost:8000).
 *
 * Returns `{ did, ethAddress, publicKey }` on success, throws on failure.
 */
export async function verifyWalletResponse(
  result: any,
  sessionId: string,
  challenge: string,
  secretKey: CryptoKey,
  didResolverUrl = 'http://localhost:8000'
): Promise<{ did: string; ethAddress: string; publicKey: string | undefined }> {
  const { encrypted } = result;

  if (!encrypted?.iv || !encrypted?.ciphertext) {
    throw new Error('Wallet response is missing the encrypted payload.');
  }

  // ── Decrypt with the QR secret ────────────────────────────────────────────
  let payload: {
    did: string;
    ethAddress: string;
    publicKey?: string;
    signature?: string;
    challenge: string;
    sessionId: string;
    walletTimestamp: number;
  };
  try {
    const iv = Uint8Array.from(atob(encrypted.iv),         c => c.charCodeAt(0));
    const ct = Uint8Array.from(atob(encrypted.ciphertext), c => c.charCodeAt(0));
    const pt = await crypto.subtle.decrypt({ name: 'AES-GCM', iv }, secretKey, ct);
    payload = JSON.parse(new TextDecoder().decode(pt));
  } catch (err: any) {
    throw new Error(`Decryption failed — wallet did not use the correct QR secret: ${err.message}`);
  }

  const { did, ethAddress, publicKey, signature, challenge: wChallenge, sessionId: wSession, walletTimestamp } = payload;

  // ── Validate fields ───────────────────────────────────────────────────────
  if (wChallenge !== challenge)   throw new Error('Challenge mismatch');
  if (wSession   !== sessionId)   throw new Error('Session ID mismatch');
  if (!did?.startsWith('did:'))   throw new Error('DID missing or malformed in payload');
  if (!ethAddress?.startsWith('0x')) throw new Error('Ethereum address missing or malformed in payload');
  if (Math.abs(Date.now() - Number(walletTimestamp)) > 5 * 60 * 1000)
    throw new Error('Wallet response timestamp expired');

  // ── Verify ECDSA signature ─────────────────────────────────────────────
  if (!signature || !publicKey) {
    throw new Error('Payload is missing a signature or public key — wallet must sign the request.');
  }
  const canonicalData = `${did}|${challenge}|${sessionId}|${walletTimestamp}`;
  let sigValid: boolean;
  try {
    sigValid = await verifyECDSA(JSON.parse(publicKey) as JsonWebKey, canonicalData, signature);
  } catch (err: any) {
    throw new Error(`Signature verification error: ${err.message}`);
  }
  if (!sigValid) {
    throw new Error('Signature verification failed — the payload may have been tampered with.');
  }

  // ── Resolve DID from authoritative source ─────────────────────────────────
  let resolvedEthAddress: string;
  try {
    const res  = await fetch(`${didResolverUrl}/resolve-did.php?did=${encodeURIComponent(did)}`);
    const json = await res.json();
    if (!json.success) throw new Error(json.message ?? 'DID not found');
    resolvedEthAddress = (json.ethAddress as string ?? '').toLowerCase();
  } catch (err: any) {
    throw new Error(`DID resolution failed for ${did}: ${err.message}`);
  }

  // ── Verify ethAddress matches DB registration ──────────────────────────────
  if (ethAddress.toLowerCase() !== resolvedEthAddress) {
    throw new Error(
      'Ethereum address does not match the registered address for this DID. ' +
      'Asset redirect attempt blocked.'
    );
  }

  return { did, ethAddress, publicKey };
}

// ─── Blockchain public-key helpers ──────────────────────────────────────────

/**
 * Convert a WebCrypto-exported P-256 JWK public key to the compressed 33-byte
 * representation stored on-chain: pkX (bytes32 hex) + pkParity (odd-y flag).
 *
 * The contract stores:
 *   pkX     = x-coordinate as bytes32 (32 B)
 *   pkParity = true → prefix 0x03 (odd y), false → prefix 0x02 (even y)
 */
export function jwkToCompressed(jwk: JsonWebKey): { pkX: string; pkParity: boolean } {
  const b64url = (s: string) =>
    Uint8Array.from(atob(s.replace(/-/g, '+').replace(/_/g, '/')), c => c.charCodeAt(0));
  const x = b64url(jwk.x!);
  const y = b64url(jwk.y!);
  const pkX = '0x' + Array.from(x).map(b => b.toString(16).padStart(2, '0')).join('');
  const pkParity = (y[y.length - 1] & 1) === 1;
  return { pkX, pkParity };
}

/**
 * Query the KYCCompliance contract for the compressed public key stored for a DID.
 *
 * @param did             The DID to look up.
 * @param contractAddress Deployed KYCCompliance address.
 * @param abi             KYCCompliance ABI (must include getPublicKey).
 * @returns 33-byte hex string ("0x02…" or "0x03…"), or "" if not registered.
 */
export async function getOnChainPublicKey(
  did: string,
  contractAddress: string,
  abi: any,
): Promise<string> {
  try {
    const { ethers } = await import('ethers');
    const provider = new ethers.BrowserProvider((window as any).ethereum);
    const kycContract = new ethers.Contract(contractAddress, abi, provider);
    const result: string = await kycContract.getPublicKey(did);
    return result; // ethers returns bytes as a hex string
  } catch (err: any) {
    console.warn('getOnChainPublicKey error:', err.message);
    return '';
  }
}
